### ISSUE TITLE
(KX autobahn)

### ISSUE THREAD

**Issue by tankirules** [maldun/autobahn#22]
Russia's election never finishes. I did propaganda for VNS and eurasianists, but the election never finalized. All that changed was the title , from "1936 russian general election " to "1937 russian general election"

**Comment by maldun** [comment]
Ok Interesting can you provide me with a save game of the bug? This would help a lot.

**Comment by tankirules** [comment]
> Ok Interesting can you provide me with a save game of the bug? This would help a lot.

It was the spot optimization mod, no need to worry :)
Thanks alot for this mod! I really wanted the r56 lategame and tech in KX as my games often go past 1945. Cheers!
