### ISSUE TITLE
game crashes when hovering over shock troop doctrine

### ISSUE THREAD

**Issue by Sexyknight** [maldun/autobahn#31]
game crashes when hovering over certain shock troop doctrine icons

**Comment by po8crg** [comment]
Yeah, I see this too.

**Comment by po8crg** [comment]
I've tried to pin this one down a bit, but I don't really understand the graphics part of modding.

Anyway, it seems to crash when opening the special forces doctrine screen after a few seconds of having it open, so you can hover over a few doctrines, but then you get a CTD.

**Comment by maldun** [comment]
Is this still relevant? I could not reproduce the issue and on the Steam Workshop page someone already confirmed it was solved with the latest KR patch.

**Comment by po8crg** [comment]
I force updated everything and that fixed it.

**Comment by Sexyknight** [comment]
just tested it, seems to be fixed now. thank you!

**Comment by maldun** [comment]
Perfect I will close the issue now with this
