### ISSUE TITLE
Game crashes when Ukraine wants to join Russian faction

### ISSUE THREAD

**Issue by maldun** [maldun/autobahn#4]
As the title says

**Comment by banburak11** [comment]
Here is my save witch crashes after accepting Ukraine into the faction, after agreeing wait ~10days(max)

https://www.dropbox.com/s/kofqoya440fm4ox/RUS_1938_08_19_20.hoi4?dl=0

**Comment by maldun** [comment]
> Here is my save witch crashes after accepting Ukraine into the faction, after agreeing wait ~10days(max)
> 
> https://www.dropbox.com/s/kofqoya440fm4ox/RUS_1938_08_19_20.hoi4?dl=0

Thanks I will have a look at it!

**Comment by maldun** [comment]
@banburak11 Hi again! I don't know how to fix it yet, but the culprit is definitely not the join event, but the Crimean fleet. As a workaround either use `deleteallunits CRM` to remove all Crimean units or load as Crimea and delete the first fleet yourself. Just be careful the game like crashes and you need pp to delete it. A trick is to select the second fleet than for some reason the game does not crash on select and you can select the first fleet and delete it. Hope this helps for now.

**Comment by banburak11** [comment]
Thank You very much for your help. Later in game it appeared I can annex ukraine without that event, but Crimea was still separate - when I tried to justify wargoal against crimean state - the same crash. That made me thinking something is about this particular fleet. 
Winning the second Weltkrieg made me claim entire Kaizermarine without problem, so only that one fleet is the problem

**Comment by maldun** [comment]
> so only that one fleet is the problem

This is also what I found out. The interesting thing is that within the save you provided me the ships in questions all have the entry `equipment ={}` which means they are basically empty. I don't know how the AI managed to build those ships as Crimea not even has ship templates to build except some weird convoy templates.

The only possibility I came up so far was that probably a wrong entry in the AI templates which contain a faulty mine sweeper destroyer template, but it is still mysterious as Germany built those without a problem. So it could also be from some buggy event from KX, it could also just be a hiccup of HOI4 itself. I can't say for certain without further information.

I will fix this AI entry for now. Nevertheless, if you could look into your save history and maybe find the reason Crimea got these faulty ships in the first place I would be thankful as maybe we could find the actual culprit.

**Comment by banburak11** [comment]
All I know about Crimea is that they've had once a war of secession against ukraine, for now its hardly possible to recreate that state of things as it would take large amounts of luck - KX likes to be unpredictable in middlegame, you never know wich path AI is going to take. Maybe in future I will approach this problem another time, for now I regard this topic as solved. 
Thank You for your time taken to investigate, I hope the results will help in development of this mod :))
