### ISSUE TITLE
Game crashes after establishing of two French states - Navy divided between those two

### ISSUE THREAD

**Issue by banburak11** [maldun/autobahn#7]
So problem similar as earlier, bugged navy causes crash.
I found out that after capitulation of French Commune there are two states being created, one by Etente and one by Kaizer.
While NFA owns the fleet physically the FRP still has the commanders avalible without the ships:

![20221202112529_1](https://user-images.githubusercontent.com/118881388/205273060-a1c920c5-d90f-4354-b1aa-8af37b69c81d.jpg)
![20221202112424_1](https://user-images.githubusercontent.com/118881388/205273077-c62e2d28-bb60-4d2c-885f-5f99bb202510.jpg)

That is the save:
https://www.dropbox.com/s/e7k3awjsekmi9sc/JAP_1942_08_14_13.hoi4?dl=0

I don't really know what to do since deleting navy didn't help much - crush still happens ~10-15 days into game

**Comment by banburak11** [comment]
Ok, I annexed FRP with NFA and deleted the navy and the crash does not occur

**Comment by maldun** [comment]
@banburak11 Hi and thanks again for your feedback! I could reproduce the issue but it seems not to be my fault this time.
The faulty fleet in your screenshot is a visual error. When I loaded your save, there was no fleet how it should be.

However there was still the crash. I searched for a bit and found out that it was the "Install Military Presence" Decisions (see screenshot) which lead to a crash. It also explained why annexing FRP solved the issue, as this makes the decisions go away. 

You should contact the KX devs about this bug as these decisions are not messing with anything from my mod, they only change compliance and resistance values in the region. I also tried if the National Ideas were the culprit, but does not seems like it. I enclosed the save as well.
[NFA_1942_09_01_02.hoi4.zip](https://github.com/maldun/autobahn/files/10144481/NFA_1942_09_01_02.hoi4.zip)


![20221202222149_1](https://user-images.githubusercontent.com/874010/205390094-35f18f83-b3c9-44c8-9aac-dd12a714c7d1.jpg)

Still thanks for reporsting! Btw. you should be able to put the saves directly here on gitlab as well for a reference as with dropbox there is always the risk of stuff vanishing ;)
[JAP_1942_08_14_13.hoi4.zip](https://github.com/maldun/autobahn/files/10144485/JAP_1942_08_14_13.hoi4.zip)

I will close this for now.
